name: Java Pipeline

on:
  push:

jobs:

  build:

    runs-on: ubuntu-latest

    steps: 
      - name: Testing

        run: echo "Hello"

      - name: build 2

        run: echo "Hello"


      - name: Finished

        run: echo "Hello"
